"""
Evennia settings file.

The available options are found in the default settings file found
here:

/home/voidfox/Projekte/evennia/evennia/evennia/settings_default.py

Remember:

Don't copy more from the default file than you actually intend to
change; this will make sure that you don't overload upstream updates
unnecessarily.

When changing a setting requiring a file system path (like
path/to/actual/file.py), use GAME_DIR and EVENNIA_DIR to reference
your game folder and the Evennia library folders respectively. Python
paths (path.to.module) should be given relative to the game's root
folder (typeclasses.foo) whereas paths within the Evennia library
needs to be given explicitly (evennia.foo).

"""

# Use the defaults from Evennia unless explicitly overridden
from evennia.settings_default import *

######################################################################
# Evennia base server config
######################################################################

# This is the name of your game. Make it catchy!
SERVERNAME = "Cursedlibrary"

LOCKDOWN_MODE = True
IN_GAME_ERRORS = True


TIME_ZONE = 'Europe/Berlin'
TIME_FACTOR = 1.0


#MULTISESSION_MODE = 2
MAX_NR_CHARACTERS = 10
GUEST_ENABLED = True
GUEST_LIST = ["Bookworm-" + str(s+1) for s in range(29)]

IRC_ENABLED = True
RSS_ENABLED = True
RSS_UPDATE_INTERVAL = 60*15 # 15 minutes




#######################################################################
# SECRET_KEY
#######################################################################
# This is the signing key for the cookies generated by Evennia's
# web interface.
#
# It is a fallback for the SECRET_KEY setting in settings.py, which
# is randomly seeded when settings.py is first created. If copying
# from here, make sure to change it!
SECRET_KEY = 'VRpy/mA?FaZ@68"tPX"hfx1>2-w%5r^s4e&[N_MG'
